name: rust-actix-api CI
on:
  push:
    branches:
      - main
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Lint
        run: cargo fmt --verbose
      - name: Test
        run: cargo test --verbose
